name: Playwright tests and report for ebay

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: run-tests
        continue-on-error: true
        run: |
          set +e
          npm test
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Zip Playwright report
        if: always()
        run: |
          if [ -d playwright-report ]; then
            zip -r playwright-report.zip playwright-report || true
          else
            echo "no playwright-report directory found"
            touch playwright-report.zip
          fi

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report.zip

  publish-pages:
    name: Publish HTML report to GitHub Pages
    runs-on: ubuntu-latest
    needs: playwright
    if: always()
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./report-zip

      - name: Unzip report
        run: |
          mkdir -p report
          if [ -f report-zip/playwright-report.zip ]; then unzip -q report-zip/playwright-report.zip -d report || true; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report/playwright-report
          publish_branch: gh-pages

      - name: Write pages link to run summary
        run: |
          owner=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          url="https://$owner.github.io/$repo/"
          echo "**Playwright HTML report:** [$url]($url)" >> $GITHUB_STEP_SUMMARY
